spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kpo-sem
    username:
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate:
      show_sql: true
      format_sql: true